# ไดเร็กทอรีหลักของโปรเจค
root = "."

# ไดเร็กทอรีที่ใช้เก็บไฟล์ชั่วคราว (ถ้ามี)
tmp_dir = "tmp"

# คำสั่งที่ใช้สำหรับการคอมไพล์โปรแกรม Go
build_cmd = "go build -o ./tmp/main ."

# คำสั่งที่ใช้ในการเรียกใช้โปรแกรมหลังจากการคอมไพล์เสร็จสมบูรณ์ (เช่น เรียกใช้โปรแกรมที่คอมไพล์ได้)
run_cmd = ["./tmp/main"]

# เวลาหน่วงเพื่อรอการประมวลผลหลังจากมีการเปลี่ยนแปลงในโค้ด (หน่วงเวลาในมิลลิวินาที)
delay = 1000

# เรียงลำดับของไฟล์ที่ต้องตรวจสอบการเปลี่ยนแปลง
[[watcher]]
paths = ["."]
